---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoportal-frontend
  labels:
    app: geoportal-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geoportal-frontend
  template:
    metadata:
      labels:
        app: geoportal-frontend
    spec:
      containers:
      - name: frontend
        image: repo.fenix.com/angular/geortal-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://api.fenix.com"
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
      imagePullSecrets:
      - name: regcred
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: geoportal-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geoportal-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
