---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoportal-back
  labels:
    app: geoportal-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geoportal-back
  template:
    metadata:
      labels:
        app: geoportal-back
    spec:
      containers:
      - name: backend
        image: repo.fenix.com/nodejs/geoprtal_back:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      imagePullSecrets:
      - name: regcred
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: geoportal-back-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geoportal-back
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
