---
apiVersion: v1
kind: ConfigMap
metadata:
  name: geoportal-back-config
data:
  NODE_ENV: "production"
  # Otras variables no sensibles aquí

---
apiVersion: v1
kind: Secret
metadata:
  name: geoportal-back-secrets
type: Opaque
stringData:
  # Ejemplo: DB_PASSWORD: "changeme"
  ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoportal-back
  labels:
    app: geoportal-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geoportal-back
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: geoportal-back
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: repo.fenix.com/nodejs/geoprtal_back:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: geoportal-back-config
            - secretRef:
                name: geoportal-back-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health   # Cambia si tu backend expone un endpoint de salud distinto
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health   # Cambia si tu backend expone un endpoint de salud distinto
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - geoportal-back
                topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: geoportal-back

---
apiVersion: v1
kind: Service
metadata:
  name: geoportal-back-service
  labels:
    app: geoportal-back
spec:
  selector:
    app: geoportal-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geoportal-back-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: api.fenix.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: geoportal-back-service
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: geoportal-back-lb
  annotations:
    metallb.universe.tf/address-pool: default-addresspool
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.10.105
  selector:
    app: geoportal-back
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: geoportal-back-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geoportal-back
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: geoportal-back-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: geoportal-back
#kubectl apply -f stack-geoportal.yaml